server:
  port: 8096
spring:
  redis:
    enabled: true
    database: 0
    password: passaz
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8    #连接池中的最大空闲连接
        min-idle: 5    #连接池中的最小空闲连接
        max-wait: 6000 #连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 10000

  datasource:
    data-username: root
    data-password: 543216
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quicklearn_data?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useTimezone=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 是否缓存preparedStatement，打开PSCache，并且指定每个连接上PSCache的大小。官方建议MySQL下建议关闭，如果用SQL防火墙 建议打开
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
